### ISSUE TITLE
Getting killed by slug slime crashes the game

### ISSUE THREAD

**Issue by Strumero** [Earthcomputer/PolyDungeons#14]
[crash-2020-07-11_16.16.35-client.txt](https://github.com/Earthcomputer/PolyDungeons/files/4907509/crash-2020-07-11_16.16.35-client.txt)

**Comment by Earthcomputer** [comment]
This is a bug with moenchantments

**Comment by Earthcomputer** [comment]
Turns out that's the modid for More Enchantments. I reported the issue to them: https://gitlab.com/biom4st3r/moenchantments/-/issues/27

**Comment by Earthcomputer** [comment]
It was fixed in More Enchantments version 1.12.2-beta4 released 22 hours ago.

**Comment by Strumero** [comment]
Thank you
